####
conf:
  bitcoin:
    env: MAIN
    data-dir: ${user.home}/.bitoin
    peers:
      - 192.168.10.1:8333
    tx-index: true
    re-index: false
#
logging:
  file:
    path: ${conf.bitcoin.data-dir}
  level:
    mode.test: debug
#