conf:
  bitcoin:
    env: REG_TEST  ## MAIN, TEST, REG_TEST
    tx-index: true
    data-dir: /tmp/can-delete
    peers:
      - 192.168.1.246:18444
##
logging:
  level:
    com.github.microwww.bitcoin.net.PeerChannelInboundHandler: DEBUG
#
