####
conf:
  ## MAIN, TEST, REG_TEST
  env: MAIN
  tx-index: true
  port: 8333
  re-index: false
  #connect:
  #  - 192.168.10.1:8333
#
logging:
  file:
    path: ${conf.data-dir}
  level:
    mode.test: debug
#