####
#
server:
  port: 8333
#
conf:
  bitcoin:
    peers:
      - 192.168.1.246:18444
#
spring:
  profiles:
    active: regtest
  application:
    name: bitcoin
#
logging:
  level:
    com.github.microwww.bitcoin: info
#
