####
#
server:
  port: 8332
#
spring:
  profiles:
    active: main
  application:
    name: bitcoin
#
conf:
  data-dir: ${user.home}/.bitoin
#
logging:
  level:
    com.github.microwww.bitcoin.net.PeerChannelInboundHandler: INFO
#
